spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true  
    properties:
      hibernate.format_sql: true
    database: postgresql
    
logging.level.org.springframework.security: TRACE
server.error.include-stacktrace: never

spring.security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:8000/realms/Teqmonic

springdoc:
  swagger-ui:
    oauth:
      client-id: springboot-be
      client-secret: TYPasarv7yqXtTn21KyTUZmD5LE1ds46
      # swagger-ui custom path
      path: /swagger-ui.html
      
# Keycloak client API calls
keycloak:
  realm: Teqmonic
  server: http://localhost:8000
  client-id: admin-cli
  grant-type: password
  user-name: clientcli
  password: system 