spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true  
    properties:
      hibernate.format_sql: true
    database: postgresql
    
logging.level.org.springframework.security: TRACE
server.error.include-stacktrace: never